In [1]:
print(1)

1

In [2]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
import pickle

In [3]:
## data loading
data = pd.read_csv("Churn_Modelling.csv")
data.head()

   RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

In [4]:
data = data.drop(columns=["RowNumber", "CustomerId", "Surname"])

In [5]:
data.head()

   CreditScore Geography  Gender  ...  IsActiveMember  EstimatedSalary  Exited
0          619    France  Female  ...               1        101348.88       1
1          608     Spain  Female  ...               1        112542.58       0
2          502    France  Female  ...               0        113931.57       1
3          699    France  Female  ...               0         93826.63       0
4          850     Spain  Female  ...               1         79084.10       0

[5 rows x 11 columns]

In [6]:
#encoding categorical data
lable_encoder_gender = LabelEncoder()
data["Gender"] = lable_encoder_gender.fit_transform(data["Gender"])

In [7]:
data

      CreditScore Geography  Gender  ...  IsActiveMember  EstimatedSalary  Exited
0             619    France       0  ...               1        101348.88       1
1             608     Spain       0  ...               1        112542.58       0
2             502    France       0  ...               0        113931.57       1
3             699    France       0  ...               0         93826.63       0
4             850     Spain       0  ...               1         79084.10       0
...           ...       ...     ...  ...             ...              ...     ...
9995          771    France       1  ...               0         96270.64       0
9996          516    France       1  ...               1        101699.77       0
9997          709    France       0  ...               1         42085.58       1
9998          772   Germany       1  ...               0         92888.52       1
9999          792    France       0  ...               0         38190.78       0

[10000 rows x 11 columns]

In [12]:
##one hot encoding for geography
from sklearn.preprocessing import OneHotEncoder
one_hot_encoder_geo = OneHotEncoder(sparse_output=False)

In [14]:
geo_encoder = one_hot_encoder_geo.fit_transform(data[["Geography"]])
geo_encoder

array([[1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       ...,
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [15]:
one_hot_encoder_geo.get_feature_names_out(["Geography"])

array(['Geography_France', 'Geography_Germany', 'Geography_Spain'],
      dtype=object)

In [16]:
geo_encoder_df = pd.DataFrame(geo_encoder, columns=one_hot_encoder_geo.get_feature_names_out(["Geography"]))

In [17]:
data = pd.concat([data, geo_encoder_df], axis=1)

In [18]:
data =data.drop(columns=["Geography"])

In [19]:
data

      CreditScore  Gender  ...  Geography_Germany  Geography_Spain
0             619       0  ...                0.0              0.0
1             608       0  ...                0.0              1.0
2             502       0  ...                0.0              0.0
3             699       0  ...                0.0              0.0
4             850       0  ...                0.0              1.0
...           ...     ...  ...                ...              ...
9995          771       1  ...                0.0              0.0
9996          516       1  ...                0.0              0.0
9997          709       0  ...                0.0              0.0
9998          772       1  ...                1.0              0.0
9999          792       0  ...                0.0              0.0

[10000 rows x 13 columns]

In [22]:
with open("lable_encoder_gender.pkl", "wb") as f:
    pickle.dump(lable_encoder_gender, f)
with open("one_hot_encoder_geo.pkl", "wb") as f:
    pickle.dump(one_hot_encoder_geo, f)

In [23]:
x = data.drop(columns=["Exited"], axis=1)
y = data["Exited"]

In [24]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

#scaling the data
scalar = StandardScaler()
x_train_scaled = scalar.fit_transform(x_train)
x_test_scaled = scalar.transform(x_test)

In [27]:
x_train_scaled

array([[ 0.35649971,  0.91324755, -0.6557859 , ...,  1.00150113,
        -0.57946723, -0.57638802],
       [-0.20389777,  0.91324755,  0.29493847, ..., -0.99850112,
         1.72572313, -0.57638802],
       [-0.96147213,  0.91324755, -1.41636539, ..., -0.99850112,
        -0.57946723,  1.73494238],
       ...,
       [ 0.86500853, -1.09499335, -0.08535128, ...,  1.00150113,
        -0.57946723, -0.57638802],
       [ 0.15932282,  0.91324755,  0.3900109 , ...,  1.00150113,
        -0.57946723, -0.57638802],
       [ 0.47065475,  0.91324755,  1.15059039, ..., -0.99850112,
         1.72572313, -0.57638802]])

In [28]:
with open("scalar.pkl", "wb") as f:
    pickle.dump(scalar, f)

In [29]:
import tensorflow as tf

WARNING:tensorflow:From c:\Users\Sushma\Desktop\projects\gen_ai_course\churn_classification\ann\lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

In [30]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
import datetime

In [33]:
## build ann

model = Sequential(
    [
        Dense(64, activation='relu', input_shape=(x_train.shape[1],)), #hl1 connected with input
        Dense(32, activation='relu'), #hl2
        Dense(1, activation='sigmoid') #output layer
    ]
)

WARNING:tensorflow:From c:\Users\Sushma\Desktop\projects\gen_ai_course\churn_classification\ann\lib\site-packages\keras\src\backend.py:873: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

In [34]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 64)                832

 dense_1 (Dense)             (None, 32)                2080

 dense_2 (Dense)             (None, 1)                 33

=================================================================
Total params: 2945 (11.50 KB)
Trainable params: 2945 (11.50 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [35]:
opt = tf.keras.optimizers.Adam(learning_rate=0.01)

In [36]:
model.compile(optimizer=opt, loss="binary_crossentropy", metrics=["accuracy"])

In [37]:
## set tensorboard
logs_dir = "logs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensoboard_callback = TensorBoard(log_dir=logs_dir, histogram_freq=1)

In [38]:
## set up early stoping
early_stopping_callback = EarlyStopping(monitor="val_loss", patience=5, restore_best_weights=True)

In [39]:
history = model.fit(x_train, y_train, validation_data=(x_test, y_test), epochs=100, callbacks=[tensoboard_callback, early_stopping_callback])

Epoch 1/100
WARNING:tensorflow:From c:\Users\Sushma\Desktop\projects\gen_ai_course\churn_classification\ann\lib\site-packages\keras\src\utils\tf_utils.py:492: The name tf.ragged.RaggedTensorValue is deprecated. Please use tf.compat.v1.ragged.RaggedTensorValue instead.

WARNING:tensorflow:From c:\Users\Sushma\Desktop\projects\gen_ai_course\churn_classification\ann\lib\site-packages\keras\src\engine\base_layer_utils.py:384: The name tf.executing_eagerly_outside_functions is deprecated. Please use tf.compat.v1.executing_eagerly_outside_functions instead.

250/250 [==============================] - 4s 7ms/step - loss: 433.4706 - accuracy: 0.6756 - val_loss: 72.8001 - val_accuracy: 0.8035
Epoch 2/100
250/250 [==============================] - 1s 5ms/step - loss: 28.1830 - accuracy: 0.7174 - val_loss: 10.2860 - val_accuracy: 0.8035
Epoch 3/100
250/250 [==============================] - 1s 5ms/step - loss: 5.1531 - accuracy: 0.7579 - val_loss: 6.4470 - val_accuracy: 0.8035
Epoch 4/100
250/250 [==============================] - 1s 4ms/step - loss: 2.5240 - accuracy: 0.7824 - val_loss: 0.4964 - val_accuracy: 0.8035
Epoch 5/100
250/250 [==============================] - 1s 5ms/step - loss: 0.9382 - accuracy: 0.7941 - val_loss: 0.4958 - val_accuracy: 0.8035
Epoch 6/100
250/250 [==============================] - 1s 6ms/step - loss: 0.5079 - accuracy: 0.7945 - val_loss: 0.4954 - val_accuracy: 0.8035
Epoch 7/100
250/250 [==============================] - 1s 4ms/step - loss: 0.5079 - accuracy: 0.7945 - val_loss: 0.4958 - val_accuracy: 0.8035
Epoch 8/100
250/250 [==============================] - 1s 5ms/step - loss: 0.5078 - accuracy: 0.7945 - val_loss: 0.4971 - val_accuracy: 0.8035
Epoch 9/100
250/250 [==============================] - 1s 4ms/step - loss: 0.5079 - accuracy: 0.7945 - val_loss: 0.4956 - val_accuracy: 0.8035
Epoch 10/100
250/250 [==============================] - 1s 5ms/step - loss: 0.5079 - accuracy: 0.7945 - val_loss: 0.4962 - val_accuracy: 0.8035
Epoch 11/100
250/250 [==============================] - 1s 5ms/step - loss: 0.5080 - accuracy: 0.7945 - val_loss: 0.4955 - val_accuracy: 0.8035

In [40]:
model.save("churn_model.h5")

c:\Users\Sushma\Desktop\projects\gen_ai_course\churn_classification\ann\lib\site-packages\keras\src\engine\training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(

In [41]:
#load tensor boadrd
%load_ext tensorboard

In [43]:
%tensorboard --logdir logs/fit

Reusing TensorBoard on port 6006 (pid 28148), started 0:02:57 ago. (Use '!kill 28148' to kill it.)