In [1]:
import tensorflow as tf
from tensorflow.keras.models import load_model
import pickle
import numpy as np
import pandas as pd

WARNING:tensorflow:From c:\Users\Sushma\Desktop\projects\gen_ai_course\churn_classification\ann\lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

In [5]:
model = load_model('churn_model.h5')

with open('lable_encoder_gender.pkl', 'rb') as f:
    label_encoder_gender = pickle.load(f)

with open('one_hot_encoder_geo.pkl', 'rb') as f:
    one_hot_encoder_geo = pickle.load(f)

with open('scalar.pkl', 'rb') as f:
    scaler = pickle.load(f)

In [7]:
input_data = {
    'CreditScore': 600,
    'Geography:': 'France',
    'Gender': 'Male',
    'Age': 40,
    'Tenure': 3,
    'Balance': 60000,
    'NumOfProducts': 2,
    'HasCrCard': 1,
    'IsActiveMember': 1,
    'EstimatedSalary': 50000
}

In [10]:
input_df = pd.DataFrame([input_data])

In [11]:
geo_encoder = one_hot_encoder_geo.transform([[input_data['Geography:']]])
geo_ecoder_df = pd.DataFrame(geo_encoder, columns=one_hot_encoder_geo.get_feature_names_out(['Geography']))
geo_ecoder_df

c:\Users\Sushma\Desktop\projects\gen_ai_course\churn_classification\ann\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

   Geography_France  Geography_Germany  Geography_Spain
0               1.0                0.0              0.0

In [12]:
input_df['Gender'] = label_encoder_gender.transform(input_df['Gender'])

In [13]:
input_df = pd.concat([input_df.drop('Geography:', axis=1), geo_ecoder_df], axis=1)

In [14]:
input_df

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_France,Geography_Germany,Geography_Spain
0,600,1,40,3,60000,2,1,1,50000,1.0,0.0,0.0

In [15]:
scaled_input = scaler.transform(input_df)

In [17]:
scaled_input

array([[-0.53598516,  0.91324755,  0.10479359, -0.69539349, -0.25781119,
         0.80843615,  0.64920267,  0.97481699, -0.87683221,  1.00150113,
        -0.57946723, -0.57638802]])

In [ ]:
probabilities = model.predict(scaled_input)[0][0]

1/1 [==============================] - 0s 41ms/step

0.23174928

In [21]:
if probabilities > 0.5:
    print(f"The customer is likely to churn with a probability of {probabilities:.2f}")
else:
    print(f"The customer is unlikely to churn with a probability of {probabilities:.2f}")

The customer is unlikely to churn with a probability of 0.23